### ISSUE TITLE
Spirit marker border colours do not update when changing colours.

### ISSUE THREAD

**Issue by pyrrhicPachyderm** [spirit-island/spirit-island-mod#119]
Reminder tokens created from power cards or the spirit panel all update their border colours, but the spirit marker doesn't.

**Comment by iakona** [comment]
most likely because the power card ones include the player color so like "Red's Call to Bloodshed" which the scripting picks up, but something called "Vital Strength of the Earth" wouldn't. in general i loath to touch color swapping code, so if you want to do something you're free to, but i'm not going to touch this, and basically chalk it up to don't swap colors after picking a spirit
